import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { WebSocketProvider } from "@/contexts/WebSocketContext";
import { AuthProviderSWR as AuthProvider } from "@/contexts/AuthContextSWR";
import { Provider } from "@/components/ui/provider";
import Navigation from "@/components/ImprovedNavigation";
import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
import AppBreadcrumb from "@/components/AppBreadcrumb";
import { ConditionalSidebar } from "@/components/ConditionalSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider defaultTheme="system" enableSystem={true}>
          <AuthProvider>
            <WebSocketProvider>
              <ClientLayoutWrapper>
                {children}
              </ClientLayoutWrapper>
            </WebSocketProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
