import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { WebSocketProvider } from "@/contexts/WebSocketContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { Provider } from "@/components/ui/provider";
import Navigation from "@/components/Navigation";
import AppBreadcrumb from "@/components/AppBreadcrumb";
import { ConditionalSidebar } from "@/components/ConditionalSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider defaultTheme="system" enableSystem={true}>
          <AuthProvider>
            <WebSocketProvider>
              <div className="flex flex-col min-h-screen">
                <Navigation />
                <ConditionalSidebar>
                  <main className="flex-1">
                    <div className="container mx-auto px-4 pt-4">
                      <Suspense fallback={<div className="h-8" />}>
                        <AppBreadcrumb />
                      </Suspense>
                    </div>
                    {children}
                  </main>
                </ConditionalSidebar>
              </div>
            </WebSocketProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
